#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib.sh
source "$SCRIPT_DIR/lib.sh"

usage() {
  cat <<'USAGE'
Usage:
  scripts/agent/deadcode.sh [--scope broad] [--base main] [--branch claude/deadcode-...] [--dry-run]

Contract:
  Input: cleanup scope (broad)
  Output: JSON with removed files/symbols report and ship pipeline result (PR URL + CI link)

Defaults:
  --task   "broad dead code cleanup"
  --commit "chore: broad dead code cleanup"
  --title  "chore: broad dead code cleanup"
USAGE
}

SCOPE="broad"
BASE_BRANCH="main"
TASK_DESC="broad dead code cleanup"
COMMIT_MSG="chore: broad dead code cleanup"
PR_TITLE="chore: broad dead code cleanup"
PR_BODY=""
BRANCH_NAME=""
DRY_RUN="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --scope)
      SCOPE="$2"
      shift 2
      ;;
    --base)
      BASE_BRANCH="$2"
      shift 2
      ;;
    --task)
      TASK_DESC="$2"
      shift 2
      ;;
    --commit)
      COMMIT_MSG="$2"
      shift 2
      ;;
    --title)
      PR_TITLE="$2"
      shift 2
      ;;
    --body)
      PR_BODY="$2"
      shift 2
      ;;
    --branch)
      BRANCH_NAME="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

[[ "$SCOPE" == "broad" ]] || die "Only --scope broad is supported"

if [[ -z "$BRANCH_NAME" ]]; then
  BRANCH_NAME="claude/deadcode-$(date +%Y%m%d-%H%M%S)"
fi

require_cmd git
require_cmd dotnet
require_cmd rg
in_git_repo || die "Not in a git repository"
ROOT="$(repo_root)"
cd "$ROOT"

if is_dirty_worktree; then
  die "Working tree is dirty. Start deadcode from a clean tree to avoid mixing unrelated changes."
fi

tmp_dir="$(mktemp -d)"
analysis_log="$tmp_dir/analyzers.log"
format_log="$tmp_dir/format.log"
pr_body_file="$tmp_dir/pr-body.md"

cleanup_temp() {
  rm -rf "$tmp_dir" >/dev/null 2>&1 || true
}
trap cleanup_temp EXIT

agent_info "Running analyzer build scan"
dotnet build Phantom/Phantom.csproj -p:EnableNETAnalyzers=true -p:AnalysisLevel=latest >"$analysis_log" 2>&1 || true

ANALYZER_FINDINGS=()
while IFS= read -r line; do
  [[ -n "$line" ]] || continue
  ANALYZER_FINDINGS+=("$line")
done < <(rg -N "warning (IDE|CS0162|CS0219|CS8321)" "$analysis_log" || true)

agent_info "Applying analyzer fixes for dead-code-adjacent diagnostics"
dotnet format analyzers Phantom/Phantom.csproj --severity warn --diagnostics IDE0005,IDE0051,IDE0052,IDE0058,IDE0059,IDE0060 >"$format_log" 2>&1 || true

REMOVED_FILES=()
for pattern in '*.orig' '*.rej' '*.bak' '*.tmp' '*.old'; do
  while IFS= read -r tracked_file; do
    [[ -n "$tracked_file" ]] || continue
    if [[ "$DRY_RUN" == "true" ]]; then
      REMOVED_FILES+=("$tracked_file (dry-run)")
    else
      git rm -f "$tracked_file" >/dev/null
      REMOVED_FILES+=("$tracked_file")
    fi
  done < <(git ls-files "$pattern")
done

CHANGED_FILES=()
while IFS= read -r file; do
  [[ -n "$file" ]] || continue
  CHANGED_FILES+=("$file")
done < <(git diff --name-only)

REMOVED_SYMBOLS=()
while IFS= read -r symbol_line; do
  [[ -n "$symbol_line" ]] || continue
  cleaned="$(printf '%s' "$symbol_line" | sed -E 's/^-[[:space:]]*//; s/[[:space:]]+/ /g')"
  REMOVED_SYMBOLS+=("$cleaned")
done < <(git diff --unified=0 -- '*.cs' | rg "^-[[:space:]]*(private|internal|protected|public)[[:space:]]+.*\\(" || true)

if [[ ${#CHANGED_FILES[@]} -eq 0 ]]; then
  printf '{\n'
  printf '  "scope": "broad",\n'
  printf '  "branch": "%s",\n' "$(json_escape "$BRANCH_NAME")"
  printf '  "no_changes": true,\n'
  printf '  "changed_files": %s,\n' "$(json_array_from_args)"
  printf '  "removed_files": %s,\n' "$(json_array_from_args "${REMOVED_FILES[@]}")"
  printf '  "removed_symbol_candidates": %s,\n' "$(json_array_from_args "${REMOVED_SYMBOLS[@]}")"
  printf '  "analyzer_findings": %s\n' "$(json_array_from_args "${ANALYZER_FINDINGS[@]}")"
  printf '}\n'
  exit 0
fi

{
  if [[ -n "$PR_BODY" ]]; then
    printf '%s\n\n' "$PR_BODY"
  fi

  printf '## Automated broad dead code cleanup\n\n'
  printf 'This PR was generated by `scripts/agent/deadcode.sh`.\n\n'
  printf '### Changed files\n'
  for file in "${CHANGED_FILES[@]}"; do
    printf -- '- `%s`\n' "$file"
  done

  printf '\n### Removed symbol candidates\n'
  if [[ ${#REMOVED_SYMBOLS[@]} -eq 0 ]]; then
    printf -- '- None detected from declaration diff parsing.\n'
  else
    count=0
    for symbol in "${REMOVED_SYMBOLS[@]}"; do
      printf -- '- `%s`\n' "$symbol"
      count=$((count + 1))
      [[ $count -ge 40 ]] && break
    done
  fi

  printf '\n### Analyzer findings (sample)\n'
  if [[ ${#ANALYZER_FINDINGS[@]} -eq 0 ]]; then
    printf -- '- None captured in analyzer output.\n'
  else
    count=0
    for finding in "${ANALYZER_FINDINGS[@]}"; do
      printf -- '- `%s`\n' "$finding"
      count=$((count + 1))
      [[ $count -ge 40 ]] && break
    done
  fi
} > "$pr_body_file"

if [[ "$DRY_RUN" == "true" ]]; then
  printf '{\n'
  printf '  "scope": "broad",\n'
  printf '  "branch": "%s",\n' "$(json_escape "$BRANCH_NAME")"
  printf '  "no_changes": false,\n'
  printf '  "changed_files": %s,\n' "$(json_array_from_args "${CHANGED_FILES[@]}")"
  printf '  "removed_files": %s,\n' "$(json_array_from_args "${REMOVED_FILES[@]}")"
  printf '  "removed_symbol_candidates": %s,\n' "$(json_array_from_args "${REMOVED_SYMBOLS[@]}")"
  printf '  "analyzer_findings": %s,\n' "$(json_array_from_args "${ANALYZER_FINDINGS[@]}")"
  printf '  "dry_run": true\n'
  printf '}\n'
  exit 0
fi

agent_info "Opening dedicated dead-code PR via ship pipeline"
ship_output="$($SCRIPT_DIR/ship.sh \
  --task "$TASK_DESC" \
  --commit "$COMMIT_MSG" \
  --title "$PR_TITLE" \
  --body-file "$pr_body_file" \
  --branch "$BRANCH_NAME" \
  --base "$BASE_BRANCH")"

printf '{\n'
printf '  "scope": "broad",\n'
printf '  "branch": "%s",\n' "$(json_escape "$BRANCH_NAME")"
printf '  "no_changes": false,\n'
printf '  "changed_files": %s,\n' "$(json_array_from_args "${CHANGED_FILES[@]}")"
printf '  "removed_files": %s,\n' "$(json_array_from_args "${REMOVED_FILES[@]}")"
printf '  "removed_symbol_candidates": %s,\n' "$(json_array_from_args "${REMOVED_SYMBOLS[@]}")"
printf '  "analyzer_findings": %s,\n' "$(json_array_from_args "${ANALYZER_FINDINGS[@]}")"
printf '  "ship_result": %s\n' "$ship_output"
printf '}\n'
